name: eric
version: 1.0.0-alpha.1
description: Read, write and modify a pubspec.yaml including retention and modifications of comments and out of spec content.
repository: https://github.com/onepub-dev/eric
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  fsm2: ^2.0.7
  meta: ^1.9.1
  path: ^1.8.3
  pub_semver: ^2.1.4
  strings: ^2.0.2
dev_dependencies: 
  lint_hard: ^3.0.0
  test: ^1.24.6
